name: 多账号刷课

on: 
  push:
    branches: [ main ]  
  schedule:
    - cron: "0 8 * * *"

jobs: 
  MultiAccountStudy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        account: [1]
      max-parallel: 2
    
    steps:
      - name: 拷贝代码
        uses: actions/checkout@v4

      - name: 设置python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安装依赖包
        run: |
          pip install -r ./requirements.txt 
      
      - name: 为账号 ${{ matrix.account }} 创建配置文件
        run: |
          cat > config_${{ matrix.account }}.ini << EOF
          [common]
          username = ${{ secrets[format('USERNAME{0}', matrix.account)] }}
          password = ${{ secrets[format('PASSWORD{0}', matrix.account)] }}
          course_list = 255731372
          speed = 1.0
          notopen_action = continue
          
          # 禁用答题功能
          [tiku]
          disable = true
          EOF
          
          echo "账号 ${{ matrix.account }} 配置文件创建完成"
          cat config_${{ matrix.account }}.ini | grep -v -E "(password|key) = " || true
      
      - name: 运行刷课脚本 - 账号 ${{ matrix.account }}
        run: |
          echo "开始执行账号 ${{ matrix.account }} 的刷课任务..."
          LOG_FILE="study_log_account_${{ matrix.account }}_$(date +%Y%m%d_%H%M%S).txt"
          python main.py -c config_${{ matrix.account }}.ini 2>&1 | tee $LOG_FILE
          
          if [ ${PIPESTATUS[0]} -eq 0 ]; then
            echo "✅ 账号 ${{ matrix.account }} 刷课任务完成"
          else
            echo "❌ 账号 ${{ matrix.account }} 刷课任务失败"
            echo "LOG_FILE=$LOG_FILE" >> $GITHUB_ENV
          fi
      
      - name: 上传失败日志（如果任务失败）
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failure-logs-account-${{ matrix.account }}
          path: ${{ env.LOG_FILE }}
          retention-days: 7

  Summary:
    runs-on: ubuntu-latest
    needs: MultiAccountStudy
    if: always()
    steps:
      - name: 任务执行总结
        run: |
          echo "多账号刷课任务执行完成"
          echo "执行时间: $(date)"
