name: 刷课

on: 
  push:
    branches: [ main ]  
  schedule:
    - cron: "0 8 * * *"

jobs: 
  Start:
    runs-on: ubuntu-latest
    steps:
      - name: 拷贝代码
        uses: actions/checkout@v3

      - name: 设置python环境
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: 安装依赖包
        run: |
          pip install -r ./requirements.txt 
      
      - name: 创建题库配置文件
        run: |
          # 创建配置文件
          cat > config.ini << EOF
          [common]
          username = ${{ secrets.USERNAME }}
          password = ${{ secrets.PASSWORD }}
          course_list = 255731372
          speed = 10.0
          notopen_action = continue
          
          [tiku]
          # 使用AI题库（DeepSeek）
          provider = AI
          
          # DeepSeek API配置
          endpoint = https://api.deepseek.com/v1
          key = ${{ secrets.DEEPSEEK_API_KEY }}
          model = deepseek-chat
          http_proxy = 
          min_interval_seconds = 3
          
          # 通用配置
          delay = 2.0
          cover_rate = 0.95
          disable = false
          submit = true
          tiku_path = ./api/data/tiku.json
          
          # 判断题选项
          true_list = 正确,对,是,true,True,是,对,正确,√,T,t,1
          false_list = 错误,错,否,false,False,错,错误,×,F,f,0
          EOF
          
          echo "配置文件创建完成"
          # 安全显示配置内容（隐藏敏感信息）
          cat config.ini | grep -v -E "(password|key) = " || true
      
      - name: 运行刷课脚本（先看视频再自动答题）
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        run: |
          echo "开始执行刷课任务..."
          echo "流程：登录 → 获取课程 → 观看视频 → 使用DeepSeek自动答题 → 完成章节"
          python main.py -c config.ini
          echo "刷课任务完成"
